### PR TITLE
Use the function form of "use strict"

### PR DESCRIPTION
**Pull request by strdr4605**
See this post [Strict Mode Is Coming To Town](https://yuiblog.com/blog/2010/12/14/strict-mode-is-coming-to-town/).

### CODE REVIEW

**Comment by BenAHammond** [comment]
Thank you for your submission! 

The increasing number of patches means I'm going to be introducing some automation and testing to ensure this stays stable going forward.

In the meantime: have you verified these changes at all?

**Comment by strdr4605** [comment]
Yes, I verified.
The simple way to verify it yourself:
in a project where you import `vue-anime`, go to `node_modules/vue-anime/index.js` add *function form of "use strict"* as in pull request and check if it works!

Or you can first write unit tests and use CI like [CircleCI](https://circleci.com/) or [TravisCI](https://travis-ci.com/), the latter is easier to configure (from my point of view). Then run my pull request in CI to see if tests passed

**Comment by BenAHammond** [comment]
Yep, that's the plan but I was going to try out the GCP automation offering for a change of pace.

This will also be my first time unit testing a Vue component, so I'm researching tooling there now.

Thank you for your submission!

**Comment by BenAHammond** [comment]
FYI I've implemented automated testing now.

https://github.com/BenAHammond/vue-anime/pull/12

**Pull request merged**
